[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npx prisma generate --schema=apps/api/prisma/schema.prisma",
  "npm run build --workspace=apps/web",
  "npm run build --workspace=apps/api"
]

[start]
cmd = "node -r tsconfig-paths/register apps/api/dist/index.js"
